spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:schema/schema.sql
      mode: always